### PR TITLE
fix error in safe_require when no unix

### PR DESCRIPTION
**Pull request by robertohuertasm**
I've been using this package with windows and was receiving errors when the safe_require function was executed, basically, due to a bad use of the separator.

### CODE REVIEW

**Comment by Klowner** [comment]
Thanks for the PR!

It looks to me like this may also potentially be an issue in [upstream casual](https://github.com/boo1ean/casual) as well, since most of your modified lines are present there as well.
```js
            providers.forEach(function(provider) {
                casual.register_provider(helpers.extend(
                    require('./providers/' + provider),
                    safe_require(__dirname + '/providers/' + locale + '/' + provider)
                ));
            });
```
If you could test regular casual on windows to verify, then submit a PR to boo1ean/casual, I'll be sure to merge it back to casual-browserify and regenerate the script.

**Comment by robertohuertasm** [comment]
@Klowner you're very welcome! 

The thing is that what they do inside the safe_require function is cross-os safe. I mean, they are using the `existsSync` from `fs`. But what you do is parsing the path. I've tested both libraries and yours is the only one giving this issues. That's why I decided to create the PR.  :wink:

**Comment by Klowner** [comment]
@robertohuertasm ohh, I see.

If your javascript bundling system supports regular `casual` then that's usually the best way to go, assuming you're able to load languages successfully.

Could I trouble you to test this branch and see if it works on your Windows environment? https://github.com/Klowner/casual-browserify/tree/browserify-nonunix

**Comment by robertohuertasm** [comment]
hey @Klowner, I've just tested and it seems to work too. :+1:

**Comment by Klowner** [comment]
Awesome, thanks again.

Fix is published as `casual-browserify@1.5.4-pre.0`

**Pull request closed without merging**
